export const VIX_MAP = {
  GOLD: '^GVZ',
  GOLDM: '^GVZ',
  SILVER: '^VXSLV',
  SILVERM: '^VXSLV',
  COPPER: 49,
  CRUDEOIL: '^OVX',
  CRUDEOILM: '^OVX',
  NATURALGAS: 62,
  NATGASMINI: 62,
  ZINC: 25,
};
